trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - .devcontainer
      - README.md

variables:
  pythonVersion: 3.10

jobs:
  - job: "Build"
    displayName: "CI - build and test"
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: UsePythonVersion@0
        displayName: "Install python"
        inputs:
          versionSpec: $(pythonVersion)

      - script: |
          pipx install poetry
        displayName: "Install poetry"

      - script: |
          poetry install
        displayName: "Install python dependencies"

      - script: |
          ruff check
          ruff format --check
        displayName: "Run linter and formatter checks"

      - script: |
          poetry run pytest --junitxml=junit/test-results.xml
        displayName: "Run pytest"

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: "**/test-*.xml"
          testRunTitle: "Publish test results"
